In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
def target_log_prob_fn(x):
    return -0.5 * tf.reduce_sum(x ** 2, axis=-1)

In [50]:
step_size = 0.01
kernel = tfp.mcmc.NoUTurnSampler(
    target_log_prob_fn=target_log_prob_fn,
    step_size=step_size
)

In [51]:
kernel = tfp.mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob_fn,
    step_size=step_size,
    num_leapfrog_steps=60
)

In [53]:
chain, trace = tfp.mcmc.sample_chain(
    kernel=kernel,
    num_results=10,
    num_burnin_steps=0,
    current_state=tf.zeros([1])
)

/Users/reneaas/miniforge3/lib/python3.9/site-packages/tensorflow_probability/python/mcmc/sample.py:339: UserWarning: Tracing all kernel results by default is deprecated. Set the `trace_fn` argument to None (the future default value) or an explicit callback that traces the values you are interested in.
  warnings.warn('Tracing all kernel results by default is deprecated. Set '


In [54]:
print(chain)

tf.Tensor(
[[-1.761608  ]
 [-1.9642444 ]
 [-0.90163964]
 [-0.91291565]
 [-1.4551407 ]
 [-1.2262373 ]
 [-1.0393379 ]
 [-1.3000093 ]
 [-0.71187305]
 [-1.6579342 ]], shape=(10, 1), dtype=float32)


In [55]:
import re

In [61]:

attributes = []
pattern = r"(\_){1,2}(\w)+(\_){0,2}"
for attr in dir(trace):
    if re.match(pattern, attr) is None:
        attributes.append(attr)
print(attributes)

trace = {attr: getattr(trace, attr) for attr in attributes}
print()

['accepted_results', 'count', 'extra', 'index', 'is_accepted', 'log_accept_ratio', 'proposed_results', 'proposed_state', 'seed']


In [62]:
print(trace)

{'accepted_results': UncalibratedHamiltonianMonteCarloKernelResults(
  log_acceptance_correction=<tf.Tensor: shape=(10,), dtype=float32, numpy=
    array([ 1.5515893 ,  0.37748712, -1.5226117 ,  0.01023032,  0.6419936 ,
           -0.30688113, -0.21171199,  0.3048929 , -0.5916153 ,  1.1209624 ],
          dtype=float32)>,
  target_log_prob=<tf.Tensor: shape=(10,), dtype=float32, numpy=
    array([-1.5516312 , -1.9291277 , -0.406477  , -0.41670743, -1.058717  ,
           -0.75182885, -0.54011154, -0.8450119 , -0.2533816 , -1.3743727 ],
          dtype=float32)>,
  grads_target_log_prob=[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
    array([[1.7616079],
           [1.9642442],
           [0.9016396],
           [0.9129155],
           [1.4551406],
           [1.2262372],
           [1.0393379],
           [1.3000091],
           [0.711873 ],
           [1.6579341]], dtype=float32)>],
  initial_momentum=[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
    array([[-3.1198134 ],
   

In [57]:
import pandas as pd

In [58]:
df = pd.DataFrame(traces)

ValueError: All arrays must be of the same length