In [1]:
import tensorflow as tf

In [2]:
import tensorflow_probability as tfp

In [6]:
dist = tfp.distributions.Normal(loc=0., scale=1.)

Metal device set to: 

2022-01-07 06:09:30.907372: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-01-07 06:09:30.908441: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



In [12]:
layers = [1, 5, 1]
kernel = []
bias = []
num_samples = 3
for n, m in zip(layers[:-1], layers[1:]):
    kernel.append(
        dist.sample(sample_shape=(num_samples, n, m))
    )
    bias.append(dist.sample(sample_shape=(num_samples,m)))

In [13]:
weights = []
for w, b in zip(kernel, bias):
    weights.extend([w, b])

In [24]:
weights

[<tf.Tensor: shape=(3, 1, 5), dtype=float32, numpy=
 array([[[ 0.94065744, -1.1573828 , -1.8728763 , -0.05894154,
           0.74315506]],
 
        [[ 0.39541802, -0.59787893, -0.68717283,  0.7306141 ,
           0.5914967 ]],
 
        [[ 0.9765441 , -1.2154157 ,  0.32481426, -1.795451  ,
          -1.0096555 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[-0.44853836,  0.8573745 ,  1.2324175 ,  1.2333242 , -0.34409985],
        [ 1.6486776 , -2.0178804 ,  0.22516067, -0.096459  ,  1.3415587 ],
        [ 0.4613919 , -1.4453946 ,  1.6711736 ,  0.8652756 , -0.3558571 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5, 1), dtype=float32, numpy=
 array([[[ 0.76968616],
         [ 0.05996678],
         [ 0.458835  ],
         [ 1.5440474 ],
         [ 1.050464  ]],
 
        [[-0.2513498 ],
         [ 0.9475734 ],
         [-0.06274645],
         [ 1.1898887 ],
         [ 0.7543455 ]],
 
        [[ 1.678421  ],
         [-0.14267032],
         [-0.1393238

In [29]:
tf.RaggedTensor(weights)

TypeError: __init__() missing 1 required positional argument: 'row_partition'

In [28]:
weights_new

[]